"use client";

import { useState, useEffect } from "react";
import { HelpCircle, Heart, Coffee, Zap, Crown, Loader2, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type PollData = {
  question: string;
  options: string[];
};

export default function DailyPollPage() {
  const [poll, setPoll] = useState<PollData | null>(null);
  const [loading, setLoading] = useState(true);
  const [votedFor, setVotedFor] = useState<number | null>(null);
  const [mockPercentages, setMockPercentages] = useState<number[]>([]);

  useEffect(() => {
    // Check for success param from Stripe
    if (typeof window !== "undefined") {
      const urlParams = new URLSearchParams(window.location.search);
      if (urlParams.get("success") === "true") {
        alert("Thank you so much for your donation! You're a legend!");
        // Clean up URL
        window.history.replaceState({}, document.title, window.location.pathname);
      }
    }

    const fetchPoll = async () => {
      try {
        const res = await fetch("/api/generate-poll");
        const data = await res.json();
        if (data.status === "success") {
          const fetchedPoll = data.data;
          setPoll(fetchedPoll);
          
          // Check local storage to see if we already voted on THIS specific question
          const savedVoteData = localStorage.getItem("perenne_daily_vote");
          if (savedVoteData) {
            const parsed = JSON.parse(savedVoteData);
            if (parsed.question === fetchedPoll.question) {
              setVotedFor(parsed.votedFor);
              setMockPercentages(parsed.mockPercentages);
              setLoading(false);
              return;
            }
          }

          // Generate mock percentages that sum to 100 for a new question
          let remaining = 100;
          const percents = Array(5).fill(0).map((_, i) => {
            if (i === 4) return remaining;
            const p = Math.floor(Math.random() * (remaining * 0.5));
            remaining -= p;
            return p;
          });
          // Shuffle them
          setMockPercentages(percents.sort(() => Math.random() - 0.5));
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    
    fetchPoll();
  }, []);

  const handleVote = (index: number) => {
    if (votedFor !== null || !poll) return;
    
    // Add user's vote to mock percentages
    const newPercentages = [...mockPercentages];
    
    setVotedFor(index);
    setMockPercentages(newPercentages);

    // Save to local storage bounded to this question
    localStorage.setItem("perenne_daily_vote", JSON.stringify({
      question: poll.question,
      votedFor: index,
      mockPercentages: newPercentages
    }));
  };

  const handleDonate = async (amount: number, productId: string) => {
    try {
      const res = await fetch("/api/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ amount, productId })
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        alert("Failed to connect to Stripe: " + data.message);
      }
    } catch (e) {
      console.error(e);
      alert("Something went wrong connecting to Stripe.");
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-12 animate-in fade-in">
      <div>
        <h1 className="text-3xl font-bold font-serif flex items-center gap-3" style={{ fontFamily: "Anthropic Serif, var(--font-merriweather), serif" }}>
          <HelpCircle className="w-8 h-8 text-primary" /> Daily Poll
        </h1>
        <p className="text-sm text-muted-foreground mt-2">A new question generated by Llama every 24 hours. Cast your vote!</p>
      </div>

      <div className="grid lg:grid-cols-3 gap-8 items-start">
        {/* Poll Area */}
        <div className="lg:col-span-2 bg-card border border-border rounded-3xl p-8 shadow-sm">
          {loading ? (
            <div className="h-64 flex flex-col items-center justify-center text-muted-foreground gap-4">
              <Loader2 className="w-8 h-8 animate-spin text-primary" />
              <p>Llama is thinking of today's question...</p>
            </div>
          ) : poll ? (
            <div className="space-y-6">
              <h2 className="text-2xl font-bold leading-tight">{poll.question}</h2>
              
              <div className="space-y-3">
                {poll.options.map((option, i) => {
                  const isVoted = votedFor === i;
                  const showResults = votedFor !== null;
                  const percentage = showResults ? (isVoted ? mockPercentages[i] + 1 : mockPercentages[i]) : 0;
                  
                  if (showResults && !isVoted) return null;

                  return (
                    <div 
                      key={i}
                      onClick={() => handleVote(i)}
                      className={cn(
                        "relative overflow-hidden rounded-xl border p-4 transition-all duration-300",
                        showResults ? "cursor-default" : "cursor-pointer hover:border-primary/50 hover:bg-primary/5",
                        isVoted ? "border-primary bg-primary/10" : "border-border bg-background"
                      )}
                    >
                      {/* Progress bar background */}
                      {showResults && (
                        <div 
                          className="absolute left-0 top-0 bottom-0 bg-primary/10 transition-all duration-1000 ease-out"
                          style={{ width: `${Math.max(percentage, 2)}%` }}
                        />
                      )}
                      
                      <div className="relative flex justify-between items-center gap-4 z-10">
                        <div className="flex items-center gap-3">
                          <div className={cn(
                            "w-5 h-5 rounded-full border flex items-center justify-center shrink-0 transition-colors",
                            isVoted ? "border-primary bg-primary text-primary-foreground" : "border-muted-foreground/30"
                          )}>
                            {isVoted && <CheckCircle2 className="w-3 h-3" />}
                          </div>
                          <span className={cn("font-medium", isVoted && "font-bold")}>{option}</span>
                        </div>
                        {showResults && (
                          <span className="font-mono font-bold text-muted-foreground">
                            {percentage}%
                          </span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
              
              {votedFor !== null && (
                <p className="text-center text-sm text-muted-foreground mt-6 animate-in fade-in">
                  Thanks for voting! Check back tomorrow for a new Llama poll.
                </p>
              )}
            </div>
          ) : (
            <div className="h-64 flex flex-col items-center justify-center text-red-500 gap-2">
              <p>Failed to load today's poll.</p>
            </div>
          )}
        </div>

        {/* Donation Area */}
        <div className="bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 rounded-3xl p-6 shadow-sm flex flex-col items-center text-center">
          <div className="w-16 h-16 bg-white dark:bg-black rounded-full flex items-center justify-center shadow-lg mb-4 border border-border">
            <Heart className="w-8 h-8 text-pink-500 fill-pink-500" />
          </div>
          
          <h2 className="text-xl font-bold mb-2">Support Perenne</h2>
          <p className="text-sm text-muted-foreground mb-8">
            Help cover server costs and API usage to keep Perenne running smoothly.
          </p>

          <div className="w-full space-y-3">
            <Button 
              onClick={() => handleDonate(40, "prod_UyuL7uhkXiAweA")}
              variant="outline" 
              className="w-full h-12 rounded-xl border-indigo-500/30 hover:bg-indigo-500/10 hover:text-indigo-600 dark:hover:text-indigo-400 group font-bold"
            >
              40p
            </Button>
            
            <Button 
              onClick={() => handleDonate(50, "prod_UyuKNoD3dVEJxW")}
              variant="outline" 
              className="w-full h-12 rounded-xl border-purple-500/30 hover:bg-purple-500/10 hover:text-purple-600 dark:hover:text-purple-400 group font-bold"
            >
              50p
            </Button>
            
            <Button 
              onClick={() => handleDonate(100, "prod_UyuH9s1lgDfznP")}
              className="w-full h-12 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-500 hover:from-indigo-600 hover:to-purple-600 text-white shadow-lg group border-none font-bold tracking-wide"
            >
              £1.00
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
